[sender]
trans_addr = "59.110.12.72:6001"
flush_interval = 5
max_sleep_time = 30

[[user_script]]
path = "python /yinzhengjie/python/usr.py"
step = 3

[[user_script]]
path = "python /yinzhengjie/python/test.py"
step = 5